QLKTXWEBSITE/Areas/AdminQL/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QLKTXWEBSITE.Models;

namespace QLKTXWEBSITE.Areas.AdminQL.Controllers
{
    //[Area("AdminQL")]
    public class ServicesController : BaseController
    {
        private readonly QlktxContext _context;

        public ServicesController(QlktxContext context)
        {
            _context = context;
        }

        // GET: AdminQL/Services
        public async Task<IActionResult> Index(string studentName, string serviceName, string month, bool? status)
        {
            // Lấy toàn bộ dữ liệu dịch vụ từ cơ sở dữ liệu
            var services = _context.Services.Include(s => s.Room).Include(s => s.Student).AsQueryable();

            // Áp dụng các điều kiện tìm kiếm nếu được cung cấp
            if (!string.IsNullOrEmpty(studentName))
            {
                services = services.Where(s => s.Student.FullName.Contains(studentName));
            }

            if (!string.IsNullOrEmpty(serviceName))
            {
                services = services.Where(s => s.ServiceName.Contains(serviceName));
            }

            if (!string.IsNullOrEmpty(month))
            {
                if (int.TryParse(month, out int monthValue))
                {
                    services = services.Where(s => s.Month == monthValue);
                }
            }

            if (status.HasValue)
            {
                services = services.Where(s => s.Status == status);
            }

            // Thực hiện truy vấn để lấy dữ liệu dịch vụ và chuyển sang danh sách
            var serviceList = await services.ToListAsync();

            return View(serviceList);
        }

        // GET: AdminQL/Services/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Services == null)
            {
                return NotFound();
            }

            var service = await _context.Services
                .Include(s => s.Room)
                .Include(s => s.Student)
                .FirstOrDefaultAsync(m => m.ServiceId == id);
            if (service == null)
            {
                return NotFound();
            }

            return View(service);
        }
        public IActionResult GetRoomsByBuilding(string building)
        {
            var rooms = _context.Rooms.Where(r => r.Building == building)
                                       .Select(r => new { value = r.RoomId, text = r.NumberRoom })
                                       .ToList();
            return Json(rooms);
        }
        public IActionResult GetStudentsByRoom(int roomId)
        {
            var students = _context.Students.Where(s => s.RoomId == roomId)
                                            .Select(s => new { value = s.StudentId, text = s.FullName })
                                            .ToList();
            return Json(students);
        }
        // GET: AdminQL/Services/Create
        public IActionResult Create()
        {
            ViewData["Building"] = new SelectList(_context.Rooms, "RoomId", "Building");

            ViewData["RoomId"] = new SelectList(_context.Rooms, "RoomId", "NumberRoom");
            ViewData["StudentId"] = new SelectList(_context.Students, "StudentId", "FullName");
            return View();
        }

        // POST: AdminQL/Services/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ServiceId,ServiceName,Month,Price,RoomId,StudentId,Status")] Service service)
        {
            if (ModelState.IsValid)
            {
                // Lấy danh sách sinh viên trong phòng đã chọn
                var studentsInRoom = await _context.Students.Where(s => s.RoomId == service.RoomId).ToListAsync();

                // Tính giá trị dịch vụ cho mỗi sinh viên
                decimal pricePerStudent;
                if (service.Price == null)
                {
                    pricePerStudent = 0;
                }
                else
                {
                    pricePerStudent = (decimal)service.Price / studentsInRoom.Count;
                }

                // Gửi dịch vụ cho từng sinh viên trong danh sách
                foreach (var student in studentsInRoom)
                {
                    // Thêm dịch vụ cho sinh viên
                    var studentService = new Service
                    {
                        RoomId = service.RoomId,
                        ServiceName = service.ServiceName,
                        StudentId = student.StudentId,
                        ServiceId = service.ServiceId,
                        Month = service.Month,
                        Price = pricePerStudent, // Giá trị dịch vụ cho mỗi sinh viên
                        Status = service.Status
                        // Các thuộc tính khác của StudentService nếu có
                    };
                    _context.Services.Add(studentService);
                }

                // Lưu các thay đổi vào cơ sở dữ liệu
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            // Nếu ModelState không hợp lệ, trả về view với dữ liệu đã nhập và danh sách phòng
            ViewData["Building"] = new SelectList(_context.Rooms, "RoomId", "Building", service.RoomId);
            ViewData["RoomId"] = new SelectList(_context.Rooms, "RoomId", "NumberRoom", service.RoomId);
            ViewData["StudentId"] = new SelectList(_context.Students, "StudentId", "FullName", service.StudentId);
            return View(service);
        }



        // GET: AdminQL/Services/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Services == null)
            {
                return NotFound();
            }

            var service = await _context.Services.FindAsync(id);
            if (service == null)
            {
                return NotFound();
            }
            ViewData["Building"] = new SelectList(_context.Rooms, "RoomId", "Building", service.RoomId);
            ViewData["RoomId"] = new SelectList(_context.Rooms, "RoomId", "NumberRoom", service.RoomId);
            ViewData["StudentId"] = new SelectList(_context.Students, "StudentId", "FullName", service.StudentId);
            return View(service);
        }

        // POST: AdminQL/Services/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ServiceId,ServiceName,Month,Price,RoomId,StudentId,Status")] Service service)
        {
            if (id != service.ServiceId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(service);
                    await _context.SaveChangesAsync();

                    // Nếu trạng thái đã thanh toán
                    if (service.Status == true)
                    {
                        // Tạo một giao dịch mới
                        var transaction = new Transaction
                        {
                            StudentId = service.StudentId,
                            Amount = service.Price,
                            Description = service.ServiceName,
                            TransactionDate = DateTime.Now
                        };

                        _context.Transactions.Add(transaction);
                        await _context.SaveChangesAsync();

                        // Nếu dịch vụ là "Phòng ở ký túc xá", cập nhật trạng thái của bản ghi Occupancy thành true
                        if (service.ServiceName == "Phòng ở ký túc xá")
                        {
                            var occupancy = _context.Occupancies.FirstOrDefault(o => o.StudentId == service.StudentId && o.RoomId == service.RoomId);
                            if (occupancy != null)
                            {
                                occupancy.Status = true;
                                _context.Update(occupancy);
                                await _context.SaveChangesAsync();
                            }
                        }
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ServiceExists(service.ServiceId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Building"] = new SelectList(_context.Rooms, "RoomId", "Building", service.RoomId);
            ViewData["RoomId"] = new SelectList(_context.Rooms, "RoomId", "NumberRoom", service.RoomId);
            ViewData["StudentId"] = new SelectList(_context.Students, "StudentId", "FullName", service.StudentId);
            return View(service);
        }



        // GET: AdminQL/Services/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Services == null)
            {
                return NotFound();
            }

            var service = await _context.Services
                .Include(s => s.Room)
                .Include(s => s.Student)

QLKTXWEBSITE/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using QLKTXWEBSITE.Models;

namespace QLKTXWEBSITE.Controllers
{
    public class LoginController : Controller
    {
        public QlktxContext _context;
        public LoginController(QlktxContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost] // POST -> khi submit form
        public IActionResult Index(LoginUser model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "Thông tin đăng nhập không hợp lệ.");
                return View(model);
            }

            var pass = model.Password;
            var dataLogin = _context.Students.FirstOrDefault(x => x.StudentCode.Equals(model.StudentCode) && x.Password.Equals(pass));
            if (dataLogin != null)
            {
                ViewBag.IsLoggedIn = true;
                HttpContext.Session.SetString("StudentLogin", model.StudentCode);
                return RedirectToAction("Details", "Students",new {id = dataLogin.StudentId});
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Thông tin đăng nhập không chính xác.");
                return View(model);
            }

        }
        [HttpGet]// thoát đăng nhập, huỷ session
        public IActionResult Logout()
        {
            HttpContext.Session.Remove("StudentLogin"); // huỷ session với key AdminLogin đã lưu trước đó

            return RedirectToAction("Create","Students");
        }
    }
}

QLKTXWEBSITE/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QLKTXWEBSITE.Models;

namespace QLKTXWEBSITE.Controllers
{
    public class NewsController : Controller
    {
        private readonly QlktxContext _context;

        public NewsController(QlktxContext context)
        {
            _context = context;
        }

        // GET: News
        public async Task<IActionResult> Index()
        {
              return _context.News != null ? 
                          View(await _context.News.ToListAsync()) :
                          Problem("Entity set 'QlktxContext.News'  is null.");
        }

        // GET: News/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.News == null)
            {
                return NotFound();
            }

            var news = await _context.News
                .FirstOrDefaultAsync(m => m.NewsId == id);
            if (news == null)
            {
                return NotFound();
            }

            return View(news);
        }

        // GET: News/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: News/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NewsId,Title,Content,PublishedDate,Author")] News news)
        {
            if (ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;
                if (files.Count() > 0 && files[0].Length > 0)
                {
                    var file = files[0];
                    var FileName = file.FileName;
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images\\news", FileName);
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        file.CopyTo(stream);
                        news.Author = "/images/news/" + FileName;
                    }
                    news.PublishedDate = DateTime.Now;
                }
                _context.Add(news);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(news);
        }

        // GET: News/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.News == null)
            {
                return NotFound();
            }

            var news = await _context.News.FindAsync(id);
            if (news == null)
            {
                return NotFound();
            }
            return View(news);
        }

        // POST: News/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("NewsId,Title,Content,PublishedDate,Author")] News news)
        {
            if (id != news.NewsId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var files = HttpContext.Request.Form.Files;
                    if (files.Count() > 0 && files[0].Length > 0)
                    {
                        var file = files[0];
                        var FileName = file.FileName;
                        var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images\\news", FileName);
                        using (var stream = new FileStream(path, FileMode.Create))
                        {
                            file.CopyTo(stream);
                            news.Author = "/images/news/" + FileName;
                        }
                    }
                    _context.Update(news);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NewsExists(news.NewsId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(news);
        }

        // GET: News/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.News == null)
            {
                return NotFound();
            }

            var news = await _context.News
                .FirstOrDefaultAsync(m => m.NewsId == id);
            if (news == null)
            {
                return NotFound();
            }

            return View(news);
        }

        // POST: News/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.News == null)
            {
                return Problem("Entity set 'QlktxContext.News'  is null.");
            }
            var news = await _context.News.FindAsync(id);
            if (news != null)
            {
                _context.News.Remove(news);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NewsExists(int id)
        {
          return (_context.News?.Any(e => e.NewsId == id)).GetValueOrDefault();
        }
    }
}

QLKTXWEBSITE/Views/Home/Aboutus.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Giới Thiệu Ký Túc Xá";
}
<head>
    <style>
        .container {
            width:80%;
            margin: auto;
            background: #fff;
            padding: 20px;
            border-radius: 5px;
        }

        h1, h2, h3 {
            color: #333;
        }

        p {
            margin-bottom: 15px;
        }
        .img{
            width:100%;
        }
        .text{
            font-size:20px
        }
        .Htext{
            font-size:30px
        }
    </style>
</head>
<body>
    <h1 class="text-center">Chào mừng bạn đến với Ký túc xá của Trường Đại Học Tài Nguyên và Môi Trường Hà Nội (HUNRE)!</h1>
    <div class="container">
        
        <img class="img" src="~/images/aboutus/anh2.jpg" />
        <p class="Htext">Một Môi Trường Sống Học Đường Tiện Nghi và An Toàn:</p>
        <p class="text">Ký túc xá của chúng tôi không chỉ là nơi nghỉ ngơi mà còn là tổ ấm thứ hai cho sinh viên. Với cơ sở vật chất hiện đại và được trang bị đầy đủ, chúng tôi cam kết mang lại một môi trường sống học đường tiện nghi và an toàn nhất cho sinh viên.</p>
        <p class="Htext"> Phòng Ở Rộng Rãi và Sạch Sẽ:</p>
        <p class="text">Các phòng ở tại ký túc xá HUNRE được thiết kế để đảm bảo sự thoải mái và riêng tư cho sinh viên. Mỗi phòng đều được trang bị đầy đủ tiện nghi cần thiết như giường ngủ, tủ đồ cá nhân, bàn làm việc và kệ sách. Sự sạch sẽ và gọn gàng luôn được chú trọng để tạo điều kiện tốt nhất cho sinh viên tập trung vào việc học tập và nghỉ ngơi.</p>
        <p class="Htext">Tiện Ích Nội Khu Đa Dạng:</p>
        <p class="text">Ký túc xá của chúng tôi cung cấp một loạt các tiện ích nội khu để đáp ứng mọi nhu cầu của sinh viên, bao gồm phòng tập gym, phòng sinh hoạt cộng đồng, khu vực giải trí, khu vực nấu ăn tự phục vụ, và khu vực giặt là. Sinh viên cũng có cơ hội kết bạn và tạo ra những kỷ niệm đáng nhớ thông qua các hoạt động xã hội và sự kiện được tổ chức tại ký túc xá.</p>
        <p class="Htext">An Toàn và Bảo Vệ:</p>
        <img class="img" src="~/images/aboutus/anh1.jpg" />
        <p class="text">Chúng tôi luôn đặt sự an toàn và bảo vệ của sinh viên lên hàng đầu. Ký túc xá được trang bị hệ thống an ninh 24/7 và có nhân viên vận hành để đảm bảo môi trường sống an toàn và yên tĩnh cho tất cả các cư dân.</p>
        <p class="Htext">Hỗ Trợ và Chăm Sóc:</p>
        <p class="text">Nhân viên của chúng tôi luôn sẵn lòng hỗ trợ và chăm sóc sinh viên trong mọi khía cạnh của cuộc sống ký túc xá. Chúng tôi cung cấp dịch vụ tư vấn, hỗ trợ kỹ thuật, và các hoạt động tạo cơ hội để sinh viên giao lưu và hòa nhập trong cộng đồng ký túc xá.</p>
        <img class="img" src="~/images/aboutus/anh3.jpg" />
        <p class="text">Ký túc xá của Trường Đại Học Tài Nguyên và Môi Trường Hà Nội không chỉ là nơi lưu trú mà còn là một phần quan trọng trong hành trình học tập và trải nghiệm của sinh viên. Chúng tôi cam kết mang lại một môi trường sống chất lượng và đầy đủ tiện nghi để giúp sinh viên phát triển toàn diện và tận hưởng những năm tháng đại học đáng nhớ.</p>
    </div>
</body>

QLKTXWEBSITE/Views/Home/Index.cshtml
@model List<QLKTXWEBSITE.Models.News>
﻿@{
    ViewData["Title"] = "Trang Chủ";
    // Tính số lượng phần tử trong danh sách tin tức
    var totalNewsCount = Model.Count();
    // Lấy 8 phần tử cuối cùng của danh sách tin tức
    var lastEightNews = Model.Skip(totalNewsCount - 8).Take(8);
}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<div id="carouselExampleControls" class="carousel slide position-relative" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/img/slide1.png" class="d-block w-100 h-100" alt="..." style="border-radius:15px; border:solid 1px green">
        </div>
        <div class="carousel-item">
            <img src="~/img/slide2.png" class="d-block w-100 h-100" alt="..." style="border-radius:15px; border:solid 1px green">
        </div>
        <div class="carousel-item">
            <img src="~/img/slide3.png" class="d-block w-100 h-100" alt="..." style="border-radius:15px; border:solid 1px green">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>
<div class="new text-center my-5">
    <h1>Chào mừng bạn đến với Ký túc xá của Trường Đại Học Tài Nguyên và Môi Trường Hà Nội (HUNRE)!</h1>
    <h2>Về chúng tôi</h2>
    <div style="margin: 0 220px 0 220px;">
        <p style="font-size:20px;">
            HUNRE là một trong những trường đại học hàng đầu tại Việt Nam chuyên về 
            lĩnh vực tài nguyên và môi trường và với rất nhiều chuyên ngành đa dạng. 
            Với hơn 60 năm xây dựng và phát triển, chúng tôi tự hào là ngôi nhà của 
            những con người tài năng và đam mê với sứ mệnh bảo vệ và bảo vệ tài nguyên
            thiên nhiên cho thế hệ tương lai.
        </p>
        <p style="font-size:20px;">
            Chúng tôi cam kết cung cấp một môi trường ở ký túc xá có học tập và nghiên cứu chất lượng 
            cao, nơi mà sinh viên có cơ hội phát triển toàn diện, hòa nhập với cộng
            đồng và đóng góp tích cực với xã hội
        </p>
    </div>
    <div style="margin: 0 320px 0 320px;">
        <a asp-action="Aboutus">Xem thêm...</a>
    </div>   
</div>
<img src="~/images/aboutus/anh2.jpg" width="100%" style="border-radius:30px;" />
<div class="section">
    <div class="proprietary container-box">
        <h1 class="my-5 text-center fw-bold">Tin Tức</h1>
        <div class="row list-projects">
            @foreach (var item in lastEightNews)
            {
                <div class="col-md-3">
                    <div class="card" style="width:100%; height:450px">
                        <div class="py-3">
                            <img src="@item.Author" alt="@item.Title" class="mb-0 w-100 text-center" style="width:100%; height:190px; border-radius:5px;" />
                        </div>
                        <div class="card-body">
                            <div class="w-100" style="height:20px;overflow: hidden;text-overflow: ellipsis;">
                                <h5 class="card-title text-center">@Html.DisplayFor(modelItem => item.Title)</h5>
                            </div>
                            <div class="w-100" style="height:100px;overflow: hidden;text-overflow: ellipsis;">
                                <p class="card-text" style="text-align:justify">@Html.DisplayFor(modelItem => item.Content)</p>
                            </div>
                            <p class="card-text float-end" style="font-size:0.6rem; color:#ccc;">@Html.DisplayFor(modelItem => item.PublishedDate)</p>
                            <br/>
                            <a asp-controller="News" asp-action="Details" asp-route-id="@item.NewsId" class="btn btn-primary">Xem thêm</a>
                        </div>
                    </div>
                </div>
            }
        </div>

        <div class="d-flex justify-content-center">
            <a asp-controller="news">
                <button type="button" class="btn btn-primary btn-lg rounded-0 my-5">
                    Xem tất cả
                </button>
            </a>
        </div>
    </div>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

QLKTXWEBSITE/Views/Home/_Beds.cshtml
@using Microsoft.EntityFrameworkCore
@model List<QLKTXWEBSITE.Models.BedOfRoom>
@{
    int RoomId = (int)(ViewData["RoomId"] ?? 0);
    string Building = (string)(ViewData["Building"] ?? "");
}
<style>
    .enabled-bed {
        background-color: #ccffcc; /* Màu xanh */
    }

    .disabled-bed {
        background-color: #ffcccc; /* Màu đỏ */
    }
</style>
<div class="row mt-3">
    <h3 style="text-align:center">Danh sách các giường phòng: @RoomId Tòa @Building</h3>
    @foreach (var bed in Model)
    {
        <div class="card fadeIn-card col-md-3 @(bed.Status == true ? "disabled-bed" : "enabled-bed") fade-in " style="border: solid 3px white; height:200px;">
            @if (bed.Status == true)
            {
                <h4>Giường số: @bed.NumberBed</h4>
                <a href="#" class="btn btn-danger btn-details" data-bed-id="@bed.BedId">Đã có sinh viên</a>
                <div class="modal-body">
                    <div id="student-details"></div>
                </div>
            }
            else
            {
                <h4>Giường số: @bed.NumberBed</h4>
                <a asp-area="StudentUser" asp-controller="Login" asp-action="Index" class="btn btn-primary btn-block btn-details">Đăng ký tài khoản</a>
            }
        </div>
    }
</div>
@section Scripts {
    <script>
        $(document).ready(function () {
            $('.btn-details').click(function () {
                var bedId = $(this).data('bed-id');

                $.ajax({
                    url: '@Url.Action("GetStudents", "Home")',
                    type: 'GET',
                    data: { BedId: bedId },
                    success: function (data) {
                        $('#student-details').html(data);
                    },
                    error: function () {
                        alert('Đã xảy ra lỗi khi tải danh sách giường.');
                    }
                });
            });
        });

        $(document).ready(function () {
            $('.card').hide().fadeIn(1000); // Hiệu ứng fade in với thời gian là 1 giây (1000 milliseconds)
        });
    </script>
}

QLKTXWEBSITE/Views/Home/_Students.cshtml
@model List<QLKTXWEBSITE.Models.Student>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>Danh sách sinh viên</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th>Họ và tên</th>
                        <th>Số điện thoại</th>
                        <!-- Thêm các cột khác nếu cần -->
                    </tr>
                </thead>
                <tbody>
                    @foreach (var student in Model)
                    {
                        <tr>
                            <td>@student.FullName</td>
                            <td>@student.PhoneNumber</td>
                            <!-- Thêm các cột khác nếu cần -->
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>